services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/application
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      SHELL: bash
      APP_ENV: dev
  db:
    image: postgres:15.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=local-user
      - POSTGRES_PASSWORD=local-password
      - POSTGRES_DB=hotels
  test-db:
    image: postgres:15.5
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=test-user
      - POSTGRES_PASSWORD=test-password
      - POSTGRES_DB=test
