"""make hotel name unique

Revision ID: a2a1ec7729c1
Revises: 4b36b8c33d1f
Create Date: 2024-07-08 18:58:29.370025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2a1ec7729c1'
down_revision = '4b36b8c33d1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_hotel_name'), 'hotel', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_hotel_name'), 'hotel', type_='unique')
    # ### end Alembic commands ###
